### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by balchef** [mzeryck/Transparent-Scriptable-Widget#1]
Getting started in this scripting and Love this script but trying to move the time to the same line as event. Cannot work it out. Any chance of a bit of help?

**Comment by mzeryck** [comment]
Find this comment in the code: `// Add an event to the widget.` (on line 327) This is the `displayEvent` function. You can change lines 331 and 332 to something like: 
```javascript
let title = widget.addText(event.title + " " + formatTime(event.startDate))
formatText(title, eventTitleSize)
```
and then remove the rest of the function.

**Comment by balchef** [comment]
Hi Max
Thank you for that. Works but I still have the time on the line below.  Not sure if I’ve done something wrong.

**Comment by mzeryck** [comment]
You can delete everything else before the ending bracket. So the whole thing would look like this:
```javascript
// Add an event to the widget.
function displayEvent(widget, event) {
  widget.addSpacer(elementSpacing)

  let title = widget.addText(event.title + " " + formatTime(event.startDate))
  formatText(title, eventTitleSize)
}
